version: "2"
services:
  practice_docker: 
    image: emothek/practice_docker
    ports: 
      - 80:3001
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://me:password@db:5432/api
      - PORT=3001
  db:
    image: postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=practicedocker